export const GET_DATA = 'GET_DATA';
export const DATA_FETCHED_SUCCESSFULLY = 'DATA_FETCHED_SUCCESSFULLY';
export const DATA_FETCHING_FAILURE = 'DATA_FETCHING_FAILURE';
export const RANGE_PRICE = 'RANGE_PRICE';
